DROP TABLE IF EXISTS drugs;

DROP TABLE IF EXISTS cohorts;

DROP TABLE IF EXISTS cohorts_drugs;

CREATE TABLE IF NOT EXISTS cohorts (id INTEGER PRIMARY KEY, age TEXT, n INTEGER);

CREATE TABLE IF NOT EXISTS cohorts_drugs (id INTEGER PRIMARY KEY, usage REAL, frequency REAL, cohort_id INTEGER, drug_id INTEGER);

CREATE TABLE IF NOT EXISTS drugs (id INTEGER PRIMARY KEY, name TEXT);
